### ISSUE TITLE
drrun never reaches target function 0 process nudged

### ISSUE THREAD

**Issue by impossibru** [googleprojectzero/winafl#125]
I am trying to fuzz a dll function used by explorer.exe
Therefore I am killing the original explorer.exe then restarting it with afl-fuzz this way 
afl-fuzz.exe -i in -o out -D C:\Dynamori_path -t 10000 --debug --coverage_module explorer.exe -fuzz_iterations 5000 -target_module shell32.dll -target_offset 0x3bf240 --nargs 2 -- explorer.exe
The address corresponds to SHELL32!CmountPoint::OnMediaArrival - SHELL32 and should be correct since I can break on it using windbg
After the timeout, winafl prints 0 Process nudged, Process -1 not found.
I am guessing it never reaches the target function and tries to kill the process.

Any idea on how to resolve that?

**Comment by ivanfratric** [comment]
Hey, I don't know about this particular target, but in general the best way to figure out what is going on is to run the debug mode first, before attempting to fuzz the target, (see readme for more details).

**Comment by overloardz** [comment]
seems his issue is the same stuff as my suggestion for pull he wants to target OnMediaArrival function on a DLL and not main binary. 
more info :
https://github.com/ivanfratric/winafl/pull/126

**Comment by overloardz** [comment]
any comment on this? @ifratric @ivanfratric @0vercl0k  would be nice to discuss.

**Comment by 0vercl0k** [comment]
Sorry I have been having a hard time to keep track of the recently reported
issues; I'll look at this thread this week-end!

Cheers

Le dim. 29 juil. 2018 à 12:18, overloardz <notifications@github.com> a
écrit :

**Comment by sarcarx** [comment]
@overloardz isnt that what target_module is used for ? Targeting modules other than the main binary ?

**Comment by 0vercl0k** [comment]
@impossibru have you investigated why it doesn't reach your target
function? Like do you expect you target function to be hit between the time
you started afl-fuzz and the time the nudge is sent?

In general, I really recommend to write targeted harnesses to avoid a bunch
of issues like this one. It's faster, easier to debug, also probably harder
to write.

Even if you didn't encounter the issue you are describing, I'd be very
surprised if you manage to get any sort of meaningful results by using
explorer in its entirety as a harness. I'd expect you to, at least, run
into speed and stability problems.

Cheers

**Comment by impossibru** [comment]
Besides the logs and debbuging the application without win-afl I don't know how to investigate more.
The target is expected to be hit just after afl-fuzz is started.
overloadz' theory seemed ok to me, but maybe someone has already managed to fuzz a loaded function rather than the executable?
Writing a harness is probably the best solution as you said but I feel like this is going to take a while for me.

**Comment by ivanfratric** [comment]
Hey all, sorry for the radio silence, I have been away for the past 2 weeks. Also, I didn't get an email notification for #126 for some reason.

@overloardz I'm not sure if I understood what you are proposing correctly, but if all you want to do is have a target function in a dll and not the main module, then it's already possible to do via target_module as @sarcarx suggested.

Otherwise, a huge +1 for writing a writing a targeted harnesses in this case instead of attempting to fuzz the entire explorer.exe. @impossibru if you let us know what exactly you are trying to fuzz we could possibly tell you more.

**Comment by impossibru** [comment]
@ivanfratric 
No worries thanks for your help.
I think the problem came from the -debug which doesn't work in afl-fuzz (only with drrun of Dynamorio?)
But I still have an issue, I know my targeted function is hit only after quite a while (a few seconds) but the timeout parameter t does not seem to delay test cases. I have an immediate :
`All test cases time out, giving up!`
Is the timeout parameter buggy? I tried to set it to 10000000000+

**Comment by ivanfratric** [comment]
-debug working without afl-fuzz is quite deliberate - it's meant to test if the instrumentation parameters are correct without actually fuzzing the target.

Regarding timeouts, yes, there might be other cases where you get this error, e.g. if the target function is never reached, or is reached but the target exits before the target function returns etc (possibly other cases I don't remember). This is the reason for the first entry in the FAQ :-) https://github.com/ivanfratric/winafl#faq

BTW a function not being documented should not prevent you from creating a function pointer to it and calling it anyway :-)

**Comment by impossibru** [comment]
What about the '-I' option? It doesn't seem to be taken in effect?

**Comment by ifratric** [comment]
This option was recently added but it probably wouldn't help in your case, as not using it and setting a -t should still reach the target function (if you don't use -I, then -t is a timeout for both reaching the target function and subsequent iterations)

**Comment by impossibru** [comment]
Okay nevermind then

**Comment by impossibru** [comment]
What about using a timeout in debug mode? Isn't that an option? Sorry to be so pigheaded I am working on a harness as well.

**Comment by ifratric** [comment]
The debug mode doesn't have a timeout (or, rather, it has an infinite timeout)

**Comment by impossibru** [comment]
I think we can just close this issue since this is really due to my using of winafl. If I find a better solution I will just post it here but it's no use of just polluting your issues.
Thanks for your help!
