### ISSUE TITLE
fuzzing test.exe failed

### ISSUE THREAD

**Issue by Flyour** [googleprojectzero/winafl#141]
when i fuzzing test.exe ,i  get timeout resposne. So I use drrun.exe to test。
my command like this   PS C:\Users\Mr.wang\Documents\WIN_AFI\DynamoRIO-Windows\bin32> `.\drrun.exe -c winafl.dll -debug  -target_module test.exe -target_offset 0x13a0  -fuzz_iterations 10 -nargs 2 -- test.exe a.txt`
I  use test_target function in test.exe as the target function ,and i think the offset is right.
but I only get this log:
```

  1 Module loaded, test.exe
  2 Module loaded, drsyms.dll
  3 Module loaded, dynamorio.dll
  4 Module loaded, drwrap.dll
  5 Module loaded, drmgr.dll
  6 Module loaded, drreg.dll
  7 Module loaded, drx.dll
  8 Module loaded, winafl.dll
  9 Module loaded, VCRUNTIME140.dll
 10 Module loaded, dtrampo.dll
 11 Module loaded, CRYPTBASE.dll
 12 Module loaded, SspiCli.dll
 13 Module loaded, KERNEL32.dll
 14 Module loaded, GDI32.dll
 15 Module loaded, ucrtbase.dll
 16 Module loaded, ADVAPI32.dll
 17 Module loaded, IMM32.dll
 18 Module loaded, RPCRT4.dll
 19 Module loaded, msvcp_win.dll
 20 Module loaded, bcryptPrimitives.dll
 21 Module loaded, KERNELBASE.dll
 22 Module loaded, win32u.dll
 23 Module loaded, msvcrt.dll
 24 Module loaded, SECHOST.dll
 25 Module loaded, gdi32full.dll
 26 Module loaded, USER32.dll
 27 Module loaded, ntdll.dll
 28 In pre_fuzz_handler
```
I only get one pre_fuzz_handler ，no post_fuz_handler.
I don't know where the problem is .
my pc is win10  17763

**Comment by hardik05** [comment]
does test function returns? if it does not, it wont go to post_fuzz.
