### ISSUE TITLE
can you use winafl or DynamoRIO on  windows10 17763 "10.0.17763.194" ?

### ISSUE THREAD

**Issue by Flyour** [googleprojectzero/winafl#150]
Actually this  problem is about DynamoRIO。I can't use DynamoRIO on my win10。
I get's this Error Message "Failed to take over all threads after multiple attempts"。
I'm sure my client is ok ，because when I use it on my vmware machine win7 or  win10 1803 it worked well。

**Comment by ifratric** [comment]
Hey, I did also notice some issues on the recent Windows versions. Here are the things you can try
 - Get a more recent DynamoRIO build from https://github.com/DynamoRIO/dynamorio/releases (this resolved the issues for me)
 - Disable any antivirus/antimalware software you have installed as it might clash with DynamoRIO.

If none of these work, then I suggest opening an issue in the DynamoRIO project (https://github.com/DynamoRIO/dynamorio) as this is generally not a good place to discuss issues that are not DR speciffic (unless someone from the community here happened to see the same issue).

Finally, if this is about the WinAFL DR client, then there is also an alternative to DR, which is to use the Intel PT backend (https://github.com/googleprojectzero/winafl/blob/master/readme_pt.md). It is kind of slow right now, but that should be mostly resolved in the upcoming patch in the next day or two (possibly even today if I manage to resolve a couple of remaining issues :-)

**Comment by Flyour** [comment]
OK , Thank you!  
I solved this  provelm ( aobut "Failed to take over all threads after multiple attempts")  by 
 "Disable any antivirus/antimalware software you have installed as it might clash with DynamoRIO."
Thank you for your advice.
