### ISSUE TITLE
zombie processes with PT mode

### ISSUE THREAD

**Issue by lzybkr** [googleprojectzero/winafl#152]
I see hundreds/thousands of zombie processes when fuzzing with `-P`. The processes are cleaned up (slowly) after stopping AFL.

**Comment by ifratric** [comment]
Ooops :-(

Should be fixed in the source now, I'll update the binaries tomorrow.

**Comment by lzybkr** [comment]
Thanks. You might consider building the binaries with `-DUSE_COLOR=1` now since PT requires Win10 anyway.

**Comment by ifratric** [comment]
Should be fixed now both in source and in binaries. Thank you very much for reporting!

Wrt USE_COLOR, I'd like the prebuilt binaries to work on older Windows versions as well. And while I did start building with Intel PT support, as far as I'm aware the binaries built that way should still be usable on older Windows versions in Dynamorio mode (please let me know if that's not the case).
