### ISSUE TITLE
_86_64  and  _WIN64

### ISSUE THREAD

**Issue by Flyour** [googleprojectzero/winafl#160]
when i read the source code of has_new_bits() in afl-fuzz.c , i find afl-fuzz.c use  __x86_64 to distinguish between  32_bit system and 64_bit system. like this:

```
#ifdef __x86_64__

  u64* current = (u64*)trace_bits;
  u64* virgin  = (u64*)virgin_map;

  u32  i = (MAP_SIZE >> 3);

#else

  u32* current = (u32*)trace_bits;
  u32* virgin  = (u32*)virgin_map;

  u32  i = (MAP_SIZE >> 2);

#endif /* ^__x86_64__ */
```

However, although i'm using a 64-bit system when i debug , i still execute like a 32-bit system.

so  on windows, we should use _WIN64 macro to distinguish between  32_bit system and 64_bit system.

Because it says in the comments that " This function is called after every exec() on a fairly large buffer, so
   it needs to be fast. We do this in 32-bit and 64-bit flavors" ，i think it's important to execute this piece of code correctly

**Comment by ifratric** [comment]
Indeed, you are correct. Could you submit a PR?

**Comment by Flyour** [comment]
enhe, ok
