### ISSUE TITLE
can you fuzzing 32bit program on 64bit system?

### ISSUE THREAD

**Issue by Flyour** [googleprojectzero/winafl#170]
when I fuzzing 32bit program on 64bit system , I get error “ WinAFL internal crash at PC 0x502863b, Please report this at. Program aborted ........"
this  problem  occurs in function create_target_process(),  actuall in "CreateProcess(NULL, cmd, NULL, NULL, inherit_handles, CREATE_SUSPENDED, NULL, NULL, &si, &pi))"  .

Do you know how to solve this problem?

**Comment by Flyour** [comment]
I think the problem is about winafl.dll , but I can't debug it

**Comment by ifratric** [comment]
Is this DynamoRIO or Intel PT mode?

**Comment by ifratric** [comment]
Ah, if it's winafl.dll then I guess DynamoRIO. You should be able to fuzz 32-bit targets on a 64-bit system, but you must also use 32-bit build of winafl.dll and point afl-fuzz to 32-bit DynamoRIO binaries.
