### ISSUE TITLE
The fuzzer is unable to get feedback from the app under DynamoRIO

### ISSUE THREAD

**Issue by andreafioraldi** [googleprojectzero/winafl#173]
Hi, I'm trying to use WinAFL for the first time and I'm not able to find new tuples on a simple vulnerable binary. I don't know if this is an issue caused by a wrong compilation of WinAFL or an issue with my system.
Would be nice if you provide a small binary to test if the build goes fine.

Returning to my problem, this is what happens:

![Capture](https://user-images.githubusercontent.com/16168186/55315101-e2834b80-546b-11e9-8df6-a9e0679db086.PNG)

I have 3 initial testcases (the 3 paths) and the fuzzer do not finds new paths. Find new paths should be easy, globetrotter.exe is a simple heap pwnable for Windows (from CSAW finals 2019).

One of the intial testcases is the following:
```
1
asd
asd
4
0
N
Y
```
To get a new path the fuzzer can just add 1 to the first byte, and this is done in the early deterministic stages of AFL but WinAFL seems to not be aware of the new edge.

My command line is the following:
```
C:\Users\Andrea\Desktop\winafl\build64\bin\Release\afl-fuzz.exe -i in -o out -m none -t 200000 -D  C:\DynamoRIO-Windows-7.1.0-1\bin64\ -- -fuzz
_iterations 5000 -target_module globetrotter.exe -target_offset 0x002030 -nargs 1 -coverage_module globetrotter.exe -- .\globetrotter.exe
```

My Windows version is 10.0.17134.648, my Visual Studio version is 15.8.9 and I'm using DynamoRIO 7.1.0

I attach the test binary and the intial inputs. I also attach the binaries that I have compiled (at commit https://github.com/googleprojectzero/winafl/commit/30e70f078ca7f51156e0c76f46c0f42365d51918):

[globetrotter.zip](https://github.com/googleprojectzero/winafl/files/3028468/globetrotter.zip)
[Release.zip](https://github.com/googleprojectzero/winafl/files/3028470/Release.zip)

**Comment by andreafioraldi** [comment]
Of course the binary works well with DynamoRIO+winafl.dll

```
C:\DynamoRIO-Windows-7.1.0-1\bin64\drrun.exe  -c winafl.dll -debug -target_module globetrotter.exe -target_offset 0x002030 -fuzz_iterations 10 -nargs 1 -- .\globetrotter.exe
```

**Comment by ifratric** [comment]
Hi, I'm not sure what is happening with your binary, but I should point out that WinAFL does come with a small test target binary (test.exe) and this is what I regularly test against.

Also, since you mention "WinAFL seems to not be aware of the new edge", you seem to want edge coverage, which you should enable via `-covtype edge` instrumentation option (WinAFL uses basic block coverage by default). I'm not sure if the sample you mentioned would result in a new bb or just new edge.

If you want to further debug the problem, you can use afl-showmap to dump AFL maps corresponding to different inputs.

**Comment by andreafioraldi** [comment]
Oh yes I didn't notice that block coverage is the default setting! I will try now -covtype edge and then report what happens. Ty

**Comment by andreafioraldi** [comment]
It is doing the same also with edge coverage, many cycles and 0 new paths.
afl-showmap reports a correct instrumentation output at first look.
I will try to add some debug prints in save_if_interesting and related functions and i will update you in case that it is a fuzzer bug.

**Comment by ifratric** [comment]
Thanks, I appreciate you looking into this!

**Comment by andreafioraldi** [comment]
Lol I opened afl-fuzz.c just now and i realized that I can't fuzz a program that takes input from stdin.
The issue is that I'm a Win32 noob :)
