### ISSUE TITLE
assert failure

### ISSUE THREAD

**Issue by lerendo** [googleprojectzero/winafl#175]
Hi! I am tryin to fuzz using the below command I am getting the error:
`ASSERT FAILURE: c:\work\winafl\source\winafl.c:947: (0) (invalid option)`

.`.\..\DynamoRIO-Windows-7.1.0-1\bin32\drrun.exe -c winafl.dll debug -target_module test_gdiplus.exe -target_method main -fuzz_iteration 10 --nargs 2 -- test_gdiplus.exe in\q`

When I try use afl-fuzz - I get the same.
What is the cause of the problem? 

I use windows 7 32bit

**Comment by ifratric** [comment]
Hey, as the error message suggests, the command line seems a bit off. What you probably want is 

`..\..\DynamoRIO-Windows-7.1.0-1\bin32\drrun.exe -c winafl.dll -debug -target_module test_gdiplus.exe -target_method main -fuzz_iterations 10 -nargs 2 -- test_gdiplus.exe in\q`

**Comment by lerendo** [comment]
> Hey, as the error message suggests, the command line seems a bit off. What you probably want is
> 
> `..\..\DynamoRIO-Windows-7.1.0-1\bin32\drrun.exe -c winafl.dll -debug -target_module test_gdiplus.exe -target_method main -fuzz_iterations 10 -nargs 2 -- test_gdiplus.exe in\q`

Ohhh, sorry. I'am stupid idiot... Just copy/paste to vm didn't works and I didnt reprint correctly. Now it works correctly, thank!!!
