### ISSUE TITLE
Unable to start IPT service

### ISSUE THREAD

**Issue by abhishiktvv** [googleprojectzero/winafl#177]
Hi , i have build the winafl with INTELPT flag enabled, the build succeeds but when i try to run i get the following error saying Unable to start IPT service, missing PT support. My version of Windows 10 is 1809 build 17763.348.

Can i please know if i am doing something wrong.missing some installation steps?
![OSBuild](https://user-images.githubusercontent.com/12431126/56718953-6b389300-675d-11e9-8b9e-19780acb387f.PNG)
![IPT](https://user-images.githubusercontent.com/12431126/56718955-6b389300-675d-11e9-8cea-5cbf4d9b7806.PNG)

**Comment by ifratric** [comment]
Does your CPU support Intel PT? Are you running WinAFL in a VM or on raw hardware?

**Comment by ifratric** [comment]
Intel PT won't work in a VM unless your VM software explicitly support it (I'm not sure if any do at this time).
