### ISSUE TITLE
Signal Object Failure

### ISSUE THREAD

**Issue by hatRiot** [googleprojectzero/winafl#178]
```
DynamoRIO 7.0.17873
Windows 7 x64
WinAFL master
```

This is less of a bug and more of a quark that I haven't been able to pin down yet; hoping someone more familiar with the code base can potentially nudge me in the right direction.

Using a custom test case (`-l`) DLL with the following command line:
```
afl-fuzz.exe -i .\in -o .\out -t 1000 -l my_dll.dll -D DynamoRIO-Windows-7.0.17873-0\bin32 -- -target_module [removed].exe -target_offset 0x40d60 -fuzz_iterations 1000 -coverage_module [removed].exe -persistence_mode in_app -- "[removed]" @@
```

Inside of my `dll_init`, I'm identifying the target process and parsing out a few data structures in a shared memory map. In order to support this, I needed to compile WinAFL manually with a small patch:

```
@@ -2591,19 +2594,18 @@ static u8 run_target(char** argv, u32 timeout) {
     }
   }

-  if (custom_dll_defined) {
-    if (!dll_init_ptr())
-      PFATAL("User-defined custom initialization routine returned 0");
-  }
-
   if(!is_child_running()) {
     destroy_target_process(0);
     create_target_process(argv);
     fuzz_iterations_current = 0;
   }

-  if (custom_dll_defined)
+  if (custom_dll_defined) {
+    if (!dll_init_ptr())
+      PFATAL("User-defined custom initialization routine returned 0");
+
     process_test_case_into_dll(fuzz_iterations_current);
+  }

   child_timed_out = 0;
   memset(trace_bits, 0, MAP_SIZE);
```

This allows the target process to be alive prior to processing `dll_init`, thus giving me an opportunity to setup some necessary structures for fuzzing. Once `dll_run` is hit, I write fuzzed data to the target process (shared memory) and signal an object (`SignalObjectAndWait`). I've been unable to successfully trigger the object, however, when run under WinAFL (`WAIT_TIMEOUT`).

For clarity:

-  I'm able to execute this fine outside of WinAFL
-  I'm able to execute this fine with the target application running under `drrun -t drcov`, outside of WinAFL
-  I know my parsing of structures is correct under WinAFL
-  I know the object handles are correct and valid

Is there something I may be missing perhaps in `winafl.dll` ? Is there any reason events/objects under WinAFL/drrun may not be signaled?

**Comment by ifratric** [comment]
Hey there, I don't know what's happening with `SignalObjectAndWait` (I could be mistaken but I don't think there's anything in `winafl.dll` specifically that would mess with it). However, I wanted to point out that normally, WinAFL uses a pipe for signalling (see WriteCommandToPipe/ReadCommandFromPipe), this has been tested and is known to work, so perhaps you could extend this mechanism (use the same pipe) to implement your signalling.

**Comment by hatRiot** [comment]
I think I understand what my issue is. It's nothing specific to signaling, but instead related to how the target process is exercised under WinAFL with custom test case processing.

I need the target process to be executing prior to `dll_run` so it can instantiate the necessary event triggers. It doesn't appear that it executes prior to this; is this the case? Using `-target_module` and `-target_offset` I assumed we'd just be waiting for these to trigger.

**Comment by ifratric** [comment]
Oh, I see now. So, it depends on which functions your DLL exports.

For example, if you export dll_run_target, then this function would get called before the target process is created (see https://github.com/googleprojectzero/winafl/blob/72204fad36621e647913c793b4cd28b64dae1510/afl-fuzz.c#L2581) and running the target process would be the responsibility of the dll. This is used mostly for implementing other instrumentation modes than those implemented by WinAFL.

The second option is to export dll_run and this function is called _after_ the target process is created (see https://github.com/googleprojectzero/winafl/blob/72204fad36621e647913c793b4cd28b64dae1510/afl-fuzz.c#L2621). This is mostly used for custom testcase delivery.

_However_, and this is what I think is causing the problems here, just because the target process is created it doesn't mean anything in it actually ran and everything might still be uninitialized. In some cases that might make sense, e.g. in network fuzzing, the target function might not even get reached unless a network connection is made using the dll first. However, apparently not in yours. In your case, it might make sense to move the `if` statement (https://github.com/googleprojectzero/winafl/blob/72204fad36621e647913c793b4cd28b64dae1510/afl-fuzz.c#L2621) to after subsequent ReadCommandFromPipe() call - that will ensure that dll_run is only called _after_ the target method has been reached.

Hope this helps.

**Comment by hatRiot** [comment]
I really appreciate your insight here. I actually need `dll_run` to run _prior_ to the target method being called, which actually seems like what happens initially...

Here's a contrived example of what I'm looking at:

```
int main(int argc, char **argv)
{
	HANDLE hMap, hEvent, hNEvent, hThread;
	LPVOID lpBuf;

	hThread = OpenThread(THREAD_ALL_ACCESS, false, GetCurrentThreadId());
	hMap = CreateFileMapping(INVALID_HANDLE_VALUE, NULL, PAGE_READWRITE, 0, 4096, L"TestMap");
	lpBuf = MapViewOfFile(hMap, FILE_MAP_ALL_ACCESS, 0, 0, 4096);
	hEvent = CreateEvent(NULL, FALSE, FALSE, NULL);

	memcpy(lpBuf, &hEvent, sizeof(HANDLE));

	printf("[SignalTest-WinAFL] Map @ %08x, waiting for trigger (event %d)...\n", lpBuf, hEvent);
	RegisterWaitForSingleObject(&hNEvent, hEvent, investigate, NULL, INFINITE, 0);
	
	SuspendThread(hThread);
	return 0;
}

VOID CALLBACK investigate(PVOID lpParameter, BOOLEAN TimerOrWaitFired)
{
	printf("[SignalTest-WinAFL] Inside investigate\n");
	
	// read from shared memory, process, etc..
}
```

Assume that the `investigate` function is the target. My `dll_run` function handles writing the fuzzed data to the shared memory map and setting the signal, thereby triggering `investigate`. I can provide demo code for the custom module if it'll help.

Testing out this example code actually revealed the event is being set at runtime under WinAFL (dbg messages mine):

```
[dbg] dll_init
[dbg] Found process @ 30404
[SignalTest-WinAFLMod] In run 0, setting event..
[SignalTest-WinAFLMod] We need to fetch event
[dbg] Remote event handle: 152
[SignalTest-WinAFL] Map @ 006f0000, waiting for trigger (event 152)...
[SignalTest-WinAFL] Inside investigate
[SignalTest-WinAFLMod] In run 1, setting event..
[SignalTest-WinAFL] Inside investigate
[SignalTest-WinAFLMod] In run 2, setting event..
[SignalTest-WinAFL] Inside investigate
SUCCESS: The process with PID 6540 has been terminated.
1 processes nudged
[!] WARNING: Test case results in a timeout (skipping)

[-] PROGRAM ABORT : All test cases time out, giving up!
         Location : perform_dry_run(), c:\users\bja.fxemp\desktop\bin\fuzzing\winafl-master\afl-fuzz.c:3062
```

But it hangs at this point and eventually times out. This implies to me that the `-target_method` or `-target_offset` is wrong, but I've tried and confirmed both to no avail. 

This is run via:
```
afl-fuzz.exe -i .\in -o .\out -t 10000+ -l SignalTest-WinAFLMod.dll -D C:\users\bja\Desktop\bin\DynamoRIO-Windows-7.0.17873-0\bin32 -- -target_module SignalTest-WinAFL.exe -target_offset 0x10f0 -fuzz_iterations 100 -coverage_module SignalTest-WinAFL.exe -- SignalTest-WinAFL.exe
```

I've also tested under debug mode:
```
c:\users\bja\Desktop\bin\DynamoRIO-Windows-7.0.17873-0\bin32\drrun.exe -c winafl.dll -debug -target_module SignalTest-WinAFL.exe -target_offset 0x10f0 -- SignalTest-WinAFL.exe
```
Once I use my external harness to manually trigger the event (simulating what `SignalTest-WinAFLMod.dll` does) I get the expected `Everything appears to be running normally.` in the resulting logs.

I think I'm missing a key component in how WinAFL/drrun starts/stops processing, but I'm just not quite sure.

**Comment by hatRiot** [comment]
Closing as it turned out to be unrelated to signals or WinAFL, really.
