### ISSUE TITLE
my speed is  0.41/sec (zzzz...)

### ISSUE THREAD

**Issue by Flyour** [googleprojectzero/winafl#181]
I met  this problem when I fuzzed a decode function in a dll。I don't know why the speed is so slowly.
I  run it in debug model:

**Module loaded, MSASN1.dll
Module loaded, CRYPT32.dll
Module loaded, VERSION.dll
Module loaded, ReaderEx.dll
Module loaded, LIBEAY32.dll
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
In pre_fuzz_handler
In OpenFileW, reading .\in\test.jp2
In post_fuzz_handler
...
Everything appears to be running normally.**

I am sure I dont' load any dll in my target_function, and the decode  function also doesn't load any dll。
other than this, I close the input  file in the end of my target_function。

So i don't know why  this happens。

To determine the problem, I commented out the call to decode function in my  target_function and the speed returned to normal.

So I want to ask, in addition to the dll load and the file not closed properly, is there any other possible reason that will cause the speed to be low?

**Comment by ifratric** [comment]
Hi, this is a difficult question to answer without knowing what is it exactly that target function does. The only other idea I have without knowing the details is that maybe, target function isn't closing the input file after reading it, which would cause WinAFL to kill the target process after each iteration in order to be able to rewrite the input file with the next sample.

You can also try using Intel PT mode, in case the slowness in this case is something specific to DynamoRIO.

**Comment by Flyour** [comment]
`int fuzztarget() {

	unsigned int* result = NULL;
	FILE *fp = NULL;
	int length = NULL;
	char* buffer = NULL;
	int count = NULL;
	unsigned int a = NULL;

	// open the file
	if (fopen_s(&fp, path, "rb") != 0){
		goto error;
	}

	// get the file length
	fseek(fp, 0, SEEK_END);
	length = ftell(fp);
	fseek(fp, 0, SEEK_SET);
	if (length <= 0){
		goto error;
	}

	// read the file to buffer
	buffer = (char *)malloc(length);
	if (buffer == NULL){
		goto error;
	}
	count = fread(buffer, 1, length, fp);
	if (count > length){
		goto error;
	}

	//decode function , my fuzz target
	result = jpeg2decode(buffer, length, &a, 0, 0);

error:
	// release buffer
	if (buffer){
		free(buffer);
	}

	// close file
	if (fp){
		fclose(fp);
	}

	//relase result buffer
	if (result){
		jpeg2destructor(result);
	}

	return 0;
}`
this is my target function ,  I close the input file  at the end。
As for the intel pt mode, I am using amd cpu, I don't know if I can use it.

**Comment by ifratric** [comment]
Hmm, I can't see anything wrong with it. When fuzzing, do you perhaps see messages (inbetween status updates) about target process being killed?

**Comment by Flyour** [comment]
Except for speed, everything looks normal, I even got some crash.

The frequency of killing the process is not high


![批注 2019-05-28 163613](https://user-images.githubusercontent.com/30471484/58463909-4c1b8f80-8167-11e9-8b12-3a34cbbb76e0.jpg)

**Comment by ifratric** [comment]
Well, if the target crashes or hangs too often (note: only unique crashes/hangs are shown and not the total number), the target process needs to be restarted for each crash/hang, which would affect the speed. But other than that, I don't have any ideas... :-(

**Comment by Flyour** [comment]
total execs is 192k, and the total crashes is 97.5k.  may be you are right. 
So how should I fix it ?
Why are there so many repeated crashes? 
Because this decoding function is too garbage?

**Comment by ifratric** [comment]
Could be. My suggestion would be to try to figure out what the most common crash cause is and then try to somehow "fix" the samples to avoid it before sending the samples to the decoder function.

**Comment by Flyour** [comment]
Thank you very much, I will try it.
