### ISSUE TITLE
It didn't work as I expected when fuzz test_netmode.exe

### ISSUE THREAD

**Issue by xinyile** [googleprojectzero/winafl#186]
Hi,

When I tried to fuzz test_netmode.exe (provided by WinAFL), I let it run for half an hour. However, WinAFL only found 5 paths and every mutated files in out/queue only has 4 bytes. WinAFL ran with those 5 files as input repeatedly and can’t find crash. 

![image (1)](https://user-images.githubusercontent.com/38596959/58808129-63370300-85e7-11e9-9480-e2937d20d545.png)
![image (2)](https://user-images.githubusercontent.com/38596959/58808137-692ce400-85e7-11e9-84a0-62d90ecb8cc0.png)

My input string is “PWNTTTTT”.  According to test_netmode.cpp, string “PWNIT…” causes crash. To my understanding, If by flipping bit, it could be very quick for WinAFL to find crash.

My command lines are:

set AFL_CUSTOM_DLL_ARGS=-U -p 7714 -a 127.0.0.1 -w 1000

afl-fuzz.exe -l custom_net_fuzzer.dll -i ..\in -o ..\out -D ..\DynamoRIO-Windows-7.1.0-1\bin32 -t 2000 -- -target_module test_netmode.exe -target_method recv_func -coverage_module test_netmode.exe -fuzz_iterations 5000 -nargs 2 -persistence_mode in_app -- ..\test_netmode.exe @@

I am very confused about this situation. Why did the content of mutated files in out/queue only have 4 bytes and why did WinAFL keep running those 5 files repeatedly and can’t find crash? 

Thank you very much.
Shirley

**Comment by mxmssh** [comment]
Yes, I have seen this problem before. It doesn't mean that something wrong with your setup. More likely this problem related to AFL's original mutation algorithm. Didn't have much time to figure that out.

**Comment by ifratric** [comment]
Yep. Additionally, it could be the case of the compiler being "smart" and merging the first 4 single-character comparisons into one DWORD comparison, which is something WinAFL won't be able to get around. To be able to better test your setup maybe start with something like 'AAAAA' and check if samples with any of the expected characters get discovered.

**Comment by xinyile** [comment]
Yes. When I started with 'AAAAA', It will discover the expected characters. But are still only 4 bytes and no crash was found. When I changed TRIM_MIN_BYTES to 5, which is used to be 4 (in config.h),  mutated files in out/queue all have 5 bytes. So it seems like mutated algorithm trims the input files first. Additionally, If I start with 4 bytes like "AAAA" with TRIM_MIN_BYTES = 5, WinAFL can't discover any expected characters. There is only one file with 'AAAA' in out/queue

**Comment by ifratric** [comment]
Hmm, looking at the code of test_netmode.cpp it seems the content of `buf` isn't initialized - I wonder if that could cause the target to read (uninitialized) data from previous iterations, which would cause the trimming algorithm to misbehave.

**Comment by xinyile** [comment]
Hi,

I met another problem when try to fuzz a server. I launched the server under DynamoRIO debug mode, before sending data to the server. .log file kept showing "In recv". After sending data through TCP protocol for only one time to the server, the server exited itself. However, I set the fuzz_iterations to 10 and as far as I concerned, data must be sent for 10 times to the server before exiting. I checked for the .log file, it shows that :

In pre_fuzz_handler
In recvfrom
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
Everything appears to be running normally.

In this case, does that mean the target function has been hitted for 10 times?

**Comment by ifratric** [comment]
Yes, `pre_fuzz_handler` runs immediately before the target function and `post_fuzz_handler` runs immediately after the target function returns.

**Comment by xinyile** [comment]
Thanks. Another thing that I want to make sure is that if "In recvfrom" means that winafl receives data from the server through UDP protocol and "In recv" means that winafl receives data from TCP protocol.

**Comment by mxmssh** [comment]
That's right recv is for TCP recvfrom is for UDP.

**Comment by xinyile** [comment]
Thank you very much. There is one warning claimed in .log file.

WARNING: Post-fuzz handler was never reached. Did the target function return normally?

I'm not quite sure what kind of return that winafl looks for. Is there any clue on how to return normally?

**Comment by mxmssh** [comment]
Well, actually this is strange. Pre and post-fuzz handlers should be reached:
```
In pre_fuzz_handler
In recvfrom
In post_fuzz_handler
```
