### ISSUE TITLE
can't find specified method in fuzz_module

### ISSUE THREAD

**Issue by suntfen** [googleprojectzero/winafl#199]
Hi,

I want to do dry run with test_gdiplus.exe with below command (DynamoRIO version is 7.1.0-1):
`C:\FuzzEnv\winafl\bin32>..\..\DynamoRIO\bin32\drrun.exe -c winafl.dll -debug -target_module test_gdiplus.exe -target_method main -fuzz_iterations 10 -nargs 2 -- test_gdiplus.exe 1.bmp`

But i got a popup with `ASSERT FAILURE: c:\work\winafl\source\winafl.c:680:to_warp (Can't find specified method in fuzz_module)`

I don't know what to do to solve this problem...😥

**Comment by ifratric** [comment]
I see you are referencing a target method by name (you're using the `target_method` and not the `target_offset` flag). This will only work if either
 - the method is exported
 - symbols are available AND WinAFL is built with Drsyms support.

In this case the method isn't exported, so that leaves symbols. Unfortunately, I had to disable Drsyms in recent WinAFL builds due to compatibility issues in recent Windows versions (in particular Windows 10 1809). However, if you wish you can still use it by building WinAFL with `-DUSE_DRSYSMS=1`.

The alternative, of course, is to use `target_offset`.

**Comment by suntfen** [comment]
Hi,

Thank you for your quick reply.

I feel a little confused about the macro, `USE_DRSYSMS` is what you mentioned above and wrote in README.md, but I found `USE_DRSYMS` is what actually used in CMakeLists.txt and winafl.c.

In fact, I tried `cmake -G"Visual Studio 14 2015" .. -DDynamoRIO_DIR=%DRIO_PATH%\cmake -DUSE_DRSYSMS=1` to rebuild winafl with Drsyms. I got same error as [issues/145](https://github.com/googleprojectzero/winafl/issues/145) and I deleted nonexistent files from "Additional Dependencies" to build winafl successfully. But I still got above popup with `ASSERT FAILURE: c:\work\winafl\source\winafl.c:680:to_warp (Can't find specified method in fuzz_module)` when I tried with new build winafl.

Is there anything wrong with my build steps?

> I see you are referencing a target method by name (you're using the `target_method` and not the `target_offset` flag). This will only work if either
> 
> * the method is exported
> * symbols are available AND WinAFL is built with Drsyms support.
> 
> In this case the method isn't exported, so that leaves symbols. Unfortunately, I had to disable Drsyms in recent WinAFL builds due to compatibility issues in recent Windows versions (in particular Windows 10 1809). However, if you wish you can still use it by building WinAFL with `-DUSE_DRSYSMS=1`.
> 
> The alternative, of course, is to use `target_offset`.

**Comment by ifratric** [comment]
Check that the pdb for your target (test_gdiplus.pdb) was also built and is in the same directory as the target. Seeing that you just rebuilt WinAFL, most likely you used the Release configuration (which is good), however the Release build does not generate pdb files - you need to build test_gdiplus using RelWithDebInfo configuration.

**Comment by suntfen** [comment]
> Check that the pdb for your target (test_gdiplus.pdb) was also built and is in the same directory as the target. Seeing that you just rebuilt WinAFL, most likely you used the Release configuration (which is good), however the Release build does not generate pdb files - you need to build test_gdiplus using RelWithDebInfo configuration.

Cool, I tried Debug configuration, and test_gdiplus.pdb is generated, and symbols are supportted. Thanks a lot!
