### ISSUE TITLE
fuzzing without in/ folder

### ISSUE THREAD

**Issue by baptistapedro** [googleprojectzero/winafl#206]
Hi,
I'm trying to fuzz a specific function from my32.dll but the function do not take a file as input, instead it has 4 parameters that I want to fuzz.
However afl-fuzz requires me  -i in/ for testcases. How can I clearly specify the afl to not use that parameter and get to fuzz the parameters instead?

```afl-fuzz -i in/  -o out -D C:\Users\gitim\Desktop\dynamorio\bin64 -t 10000 -- -coverage_module my32.dll -target_module C:\Users\gitim\source\repos\godoit\Debug\godoit.exe -target_method fuzz_create -nargs 4 -- godoit.exe  -1 -1 1 1 @@```

With that command I'm receiving ```[-] Looks like there are no valid test cases in the input directory! The fuzzer
    needs one or more test case to start with - ideally, a small file under
    1 kB or so. The cases must be stored as regular files directly in the
    input directory.

[-] PROGRAM ABORT : No usable test cases in 'in/'
         Location : read_testcases(), c:\work\winafl\source\afl-fuzz.c:1633```

**Comment by ifratric** [comment]
WinAFL does indeed require input files (otherwise there is nothing to mutate :-). What I would do is to write a harness that loads an input file, converts the content to the parameters you need and calls the target function.

**Comment by baptistapedro** [comment]
It isn't totally clear on my head, mind to do a code snippet as sample of how would it be?

**Comment by KA2010** [comment]
@ifratric 
Could please give me example on your solution suggestion, I have same issue and I like your suggestion but could give example of how to do it ?
