### ISSUE TITLE
Timed out but "Everything appears to be running normally."

### ISSUE THREAD

**Issue by lolblat** [googleprojectzero/winafl#214]
Hello all,
I am trying to fuzz a GUI application, I run this command: 
`afl-fuzz.exe -i in -o out -t 10000 -D DynamoRIO\bin64 -- -debug -coverage_module PhotoViewer.dll -fuzz_iterations 10 -target_module WindowsImageHarnest.exe -target_offset 0x1150 -nargs 1 -- WindowsImageHarnest.exe @@
`
I read the log file created by the fuzzer and I see 10 "in pre_fuzz_handler" and 10 "in post_fuzz_handler", and in the end of the log I see: "Everything appears to be running normally.".
One thing that is weird about the log file is the coverage map, its only null.
When I tried to run the program in the way its written in "readme_dr", everything worked well, but the coverage map is still only null.

I work on VM with Windows build 1903, the Dynamorio was cloned and built, I didnt download the binaries, I cloned the rep and build it.

Thank you for your help :).

**Comment by ifratric** [comment]
Hey,

You shouldn't use `-debug` flag with afl-fuzz.exe, only with drrun.exe like in the examples. This is a possible reason for the timeouts.

As for the empty coverage map, the usual reason for this is that none of the coverage modules (`PhotoViewer.dll` in your case) were reached during processing of the sample. If that helps, note that you can add multiple coverage modules.

**Comment by lolblat** [comment]
Great it worked! Thank you
