### ISSUE TITLE
It's there any idea to support socket based client fuzzing? 

### ISSUE THREAD

**Issue by boofish** [googleprojectzero/winafl#217]
Why winafl do not use NtCreateThread or CreateProcess method to recover program state, just like Linux AFL's forkserver? I want to have a try, but I don't understand the problem.

**Comment by Flyour** [comment]
if(!CreateProcess(NULL, cmd, NULL, NULL, inherit_handles, CREATE_SUSPENDED, NULL, NULL, &si, &pi)) {
    FATAL("CreateProcess failed, GLE=%d.\n", GetLastError());
  }

**Comment by boofish** [comment]
> ` if(!CreateProcess(NULL, cmd, NULL, NULL, inherit_handles, CREATE_SUSPENDED, NULL, NULL, &si, &pi)) { FATAL("CreateProcess failed, GLE=%d.\n", GetLastError()); }`
Thank you!
