### ISSUE TITLE
The program took more than 100000 ms to process one of the initial test cases

### ISSUE THREAD

**Issue by sum-catnip** [googleprojectzero/winafl#218]
Hey,

im fuzzing a dll with dynamicRIO.
The initial test works perfectly fine:
`drrun.exe -c winafl.dll -debug -fuzz_iterations 3 -target_module harness.exe -target_offset 0x1C9E0 -nargs 0 -- .\harness.exe xzy`

it loads my harness
> Module loaded, harness.exe

it loads my coverage target
> Module loaded, coverage.dll

pre and postfuzz:
```
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
In pre_fuzz_handler
In post_fuzz_handler
Everything appears to be running normally.
Coverage map follows:
...
```

everything is done in under a second.

When i start the actual fuzzing however, it tells me that the program took more than 100000 ms to process the test case (at the first run).
```
[*] Attempting dry run with 'id_000000'...
[-] The program took more than 100000 ms to process one of the initial test cases.
...
```

starting winafl with:
`.\afl-fuzz.exe -debug -i testfiles -o out -D %RIO% -t 100000 -- -debug -coverage_module coverage.dll -fuzz_iterations 1 -target_module harness.exe -target_offset 0x1C9E0 -nargs 0 -- .\harness.exe @@`
the dynamicRIO generated logfile looks exactly the same as in the dynamicRIO testrun
> Everything appears to be running normally.

My harness is also creating a logfile, which tells me that `fuzz() took 50658 microseconds` so its not my harness.

The fuzz method is exported with `extern "C" __declspec(dllexport) int fuzz();` and returns 0. It does not exit the process.

Any other thing i could try? Maybe i could try custom testcase processing, but will it work the same way, in terms of code coverage?

**Comment by ifratric** [comment]
Hey, you should remove the -debug flag from afl-fuzz command line, that flag is only meant to be used with drrun.exe directly.

**Comment by sum-catnip** [comment]
oooooh shiiiiiet im such an idiot :'D. welp it works now, thanks :D. Also, sorry for hijacking this issue but i was wondering. If i use the custom test case processing, could i gain a performance benefit because i dont have to load the file from disk or does it have any other drawbacks?

**Comment by ifratric** [comment]
In theory, yes it's possible, but I don't have any measurements on that or how it would compare vs. for example fuzzing from a ramdisk.

**Comment by sum-catnip** [comment]
Aight. I'll just try then, thanks again :3
