### ISSUE TITLE
Program under test may change state when recover from a fuzzing iteration

### ISSUE THREAD

**Issue by boofish** [googleprojectzero/winafl#224]
Hi, I found WinAFL may change program state when a fuzzing iteration complete,

especially when a target function operate on global variables.

i.e.. 

```
#define BUFSIZE 4096

int global_var = 0;

void parse_file(char *filename)
{
	char buf[BUFSIZE+1];
	memset(buf,0,BUFSIZE+1);
	FILE *fp = fopen(filename, "rb");
	fgets(fp, BUFSIZE, buf);

	if (global_var < 10)
	{
		handle_content(buf);
		global_var += 1;

	}else{
		.....
	}

}

```
every iteration the program executes, the program state will change, which means the fuzzing process is unstable.
I have checked the source code of winafl.c, and found routine of program state recovery depends on the following:
```

mc->xsp = fuzz_target.xsp;
mc->pc = fuzz_target.func_pc;
drwrap_redirect_execution(wrapcxt);

```
Obviously it only record the pc and registers of the program state, and do not keep the memory consistent(i.e. heap, stack and global memory). Once a fuzzing iteration complete executing, these memory may be changed. redirect execution to next fuzzing iteration will be some different.

When fuzzing a protocol implementation program, especially for a session communication, redirect execution routine will casue side effects.

Is there any idea for stable fuzzing? how to keeping program state consistent thoroughly?

**Comment by ifratric** [comment]
Hi,
Yes, that's a known "feature" of how persistence is implemented in WinAFL. The reasoning here is, if the target needs more state-restoring than WinAFL provides by default, it is better to implement custom state-restoring for a particular target, than to attempt to implement a generic solution (which would cause a significant drop in performance).

**Comment by boofish** [comment]
Thanks!
Implementing custom state-restoring is non-trivial work, especially for windows environment:)
