### ISSUE TITLE
Run drrun.exe with my executable would return 000 111 for 10 times

### ISSUE THREAD

**Issue by guilanl** [googleprojectzero/winafl#225]
Hi, 

I started to try winafl to fuzz a small executable as a test. 
I downloaded winafl and also DynamoRIO. 
Then I compiled a executable file with Visual Studio 2017. 
The program to be fuzzed is as below: 

`#include "stdafx.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

FILE* fp;

 void open_file()
 {
	 if ((fp = fopen("myfile.txt", "rb")) == NULL)
	 {
		 printf("cant open the file");
		 return;
	 }
 }

 int main()
 {

	 int buffer[4];

	 open_file();

	 if (fp)
	 {
		 fseek(fp, 0, SEEK_END);
		 int fsize = ftell(fp); 

		 fseek(fp, 0, SEEK_SET);  /* same as rewind(f); */
								  //rewind(pfile);

		 char *string = (char *)malloc(fsize * sizeof(char) + 1);

																
		 memset(string, 0, fsize * sizeof(char) + 1);

		 int result = fread(string, 1, fsize, fp);

		 for (int i = 0; i<2; i++)
			 printf("%d\n", string[i]);
	 }

	 return 0;
 }`

I compiled the program with "x86 debug ".

According to guide, then I started to run the below drrun.exe command:
C:\test\DynamoRIO-Windows-7.1.0-1\bin32>drrun.exe -c winafl.dll -debug -target_module test_main.exe -target_offset 0x118B0 -fuzz_iterations 10 -nargs 2 -- test_main.exe myfile.txt
100
111
100
111
100
111
100
111
100
111
100
111
100
111
100
111
100
111
100
111

I got many "000 111" printed. 

I would like to know what does this mean?
Does that mean this step is success or not?

**Comment by ivanfratric** [comment]
Looks OK to me - I assume myfile.txt contains the strings that get printed (100 and 111) and the command line you used instructs DynamoRIO to loop over target function (presumably "main") 10 times, thus you get this output printed 10 times.

**Comment by guilanl** [comment]
Thanks for your reply.

**Comment by guilanl** [comment]
Hi @ivanfratric ,

Since the above steps is OK, then I go to with fuzzing.

I used the following command: 
afl-fuzz.exe -i in -o out -D C:\test\DynamoRIO-Windows-7.1.0-1\bin32 -t 20000 -coverage_module test_main.exe -fuzz_iterations 10 -target_module test_main.exe -target_offset 0x118B0 -nargs 2 -- test_main.exe @@

It didn't start fuzzing but just print the usage prompt. 

I followed the steps in: 
https://github.com/googleprojectzero/winafl/blob/master/readme_dr.md
to compose the command. 
Could you please tell me what is wrong with the command here. 

PS:
Does "-coverage_module" needed here?  What should I fill to it if it is necessary? 
Should I have the "in" and "out" folder created at first? 

Thanks for your help here.

**Comment by ivanfratric** [comment]
There needs to be another `--` between afl-fuzz and instrumentation options. Check the documentation for the command line format and the examples.

The `-coverage_module` option instructs WinAFL from which module(s) to extract coverage. Since (Win)AFL is a coverage-guided fuzzer, this is needed for normal fuzzing operation and omitting it will result in "no instrumentation detected" error.

**Comment by guilanl** [comment]
Hi @ivanfratric , 

Thanks for the help. 

I did some modification according to your comments , the fuzzer started to run, but I got the below timeout issue. 

C:\test\winafl-master\bin32>afl-fuzz.exe -i in -o out -D C:\test\DynamoRIO-Windows-7.1.0-1\bin32 -t 20000 -- -coverage_module test_main.exe -fuzz_iterations 10 -target_module test_main.exe -target_offset 0x118B0 -nargs 2 -- test_main.exe @@
WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
[+] You have 4 CPU cores and 0 runnable tasks (utilization: 0%).
[+] Try parallel jobs - see docs\parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Setting up output directories...
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
SUCCESS: The process with PID 424 has been terminated.
1 processes nudged

[-] The program took more than 20000 ms to process one of the initial test cases.
    Usually, the right thing to do is to relax the -t option - or to delete it
    altogether and allow the fuzzer to auto-calibrate. That said, if you know
    what you are doing and want to simply skip the unruly test cases, append
    '+' at the end of the value passed to -t ('-t 20000+').

[-] PROGRAM ABORT : Test case 'id_000000' results in a timeout
         Location : perform_dry_run(), c:\work\winafl\source\afl-fuzz.c:2951

What is the reason of the timeout issue?

Thanks.

**Comment by ivanfratric** [comment]
Such errors are best diagnosed with the help of a debug log, you should re-run the debug mode and inspect the log.

**Comment by guilanl** [comment]
I did some modification in my program and it finally started fuzzing. 

Sometimes, it runs normally, and sometimes, it still have timeout issue. 

Still thank you for your reply.
