### ISSUE TITLE
PROGRAM ABORT : No instrumentation detected

### ISSUE THREAD

**Issue by MrNasro** [googleprojectzero/winafl#229]
Hello,

[afl.vulnerablex32.exe.08532.0000.proc.log](https://github.com/googleprojectzero/winafl/files/4050768/afl.vulnerablex32.exe.08532.0000.proc.log)
[sample.txt](https://github.com/googleprojectzero/winafl/files/4050769/sample.txt)

I am just trying to experiment with it but nothing seems to be working, here is my environment:

- Windows 10 64bit
- Compiled 32bit WinAFL and dynamoRIO from source using VS 2013

The program I wanted to experiment with is (it crashes when either BEEF or DEADBEEF is read from a file) (compiled to a 32bit exe):

```
// ConsoleApplication10.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <windows.h>
#include <stdio.h>
#include <signal.h>
#define FILELEN 15

extern "C" __declspec(dllexport) int main(int argc, char **argv);

void FuzzMe(byte* bytes, unsigned int fileSize)
{
	if (fileSize >= 2)
	{
		if (bytes[0] == 0xBE)
		{
			if (bytes[1] == 0xEF)
			{
				// CRASH
				*(DWORD*)0 = 1;
				
			}
		}
	}
	if (fileSize >= 4)
	{
		if (bytes[0] == 0xDE)
		{
			
			if (bytes[1] == 0xAD)
			{
				if (bytes[2] == 0xBE)
				{
					
					if (bytes[3] == 0xEF)
					{
						// CRASH
						*((unsigned int*)0) = 0xDEAD;
						*(DWORD*)0 = 1;
					}
				}
			}
		}
	}
}

int main(int argc, char **argv){
	FILE *f;
	char* fName;
	char *array;
	long fSize;
	int result;
         if (argv[1] != NULL){
	    fName = argv[1];
    	    if ((f = fopen(fName, "rb")) == NULL)
	    {
		    return 0;
	    }else{

	        fseek(f, 0, SEEK_END);
	        fSize = ftell(f);
	        rewind(f);
	        array = (char *)malloc(fSize + 1);

	        fread(array, sizeof(char), 4, f);
	        FuzzMe((byte*)array, fSize);
	        free(array);
	        fclose(f);
	        return 0;
            }
      }
}
```

I am running WinAFL using the following command (I have also tried  -nargs 0):

```
afl-fuzz.exe -i in -o out -t 10000 -D C:\DynamoRIO\build\bin32 -- -covtype edge -fuzz_iterations 100000 -coverage_module vulnerablex32.exe -target_module vulnerablex32.exe -nargs 1 -target_method main -- vulnerablex32.exe @@
```

inside in/ there’s a file that contains “DEFF” bytes (find it attached too) I get the following output:

```
WinAFL 1.16 by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
[+] You have 4 CPU cores and 0 runnable tasks (utilization: 0%).
[+] Try parallel jobs - see docs\parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...

[-] PROGRAM ABORT : No instrumentation detected
        Location : perform_dry_run(), C:\winafl\afl-fuzz.c:3026
```

Find the debug output attached too. Please help me identify the issue!

**Comment by expend20** [comment]
vulnerable32 or vulnerablex32?

**Comment by MrNasro** [comment]
> vulnerable32 or vulnerablex32?

Sorry it's a mistype "-coverage_module vulnerablex32.exe"

**Comment by expend20** [comment]
Is it working after that fix?

**Comment by MrNasro** [comment]
Nope, I meant it was a mistype in the post not the command I used

**Comment by expend20** [comment]
You should see line line "instrumenting vulnerablex32.exe module" in debug log. Could you share the binary?

**Comment by MrNasro** [comment]
> You should see line like "instrumenting vulnerablex32.exe module" in debug log. Could you share the binary?

Sure find it attached, rename ".exe.txt" to ".exe" since I cannot attach ".exe" here. If you do not want to run the binary for security purposes find the source code above.

Thank you for working on this!

[vulnerablex32.exe.txt](https://github.com/googleprojectzero/winafl/files/4050906/vulnerablex32.exe.txt)

**Comment by expend20** [comment]
I don't have debugging runtime for vs2013 (MSVCR120D.dll) could you share a release build? I would look at it at runtime.

**Comment by expend20** [comment]
Quick note, unrelated to main thread, don't use `exit(0)` since winafl won't be able to catch that via `post_fuzz_handler` and will restart the process if that branch hit.

**Comment by MrNasro** [comment]
> Quick note, unrelated to main thread, don't use `exit(0)` since winafl won't be able to catch that via `post_fuzz_handler` and will restart the process if that branch hit.

I now replaced `exit(1)` with `return 0` in the original post and tried that instead but I am still getting the same error in WinAFL.

Here is the release build /w replaced `exit` to `return` (rename to `.exe`)
[vulnerablex32-release.exe.txt](https://github.com/googleprojectzero/winafl/files/4050947/vulnerablex32-release.exe.txt)

**Comment by expend20** [comment]
Give a try `-coverage_module ConsoleApplication10.exe`

**Comment by MrNasro** [comment]
> Give a try `-coverage_module ConsoleApplication10.exe`

OMG, that worked, but though?

**Comment by expend20** [comment]
Binary magic :) The reason behind this is that the export directory contains the name which is different from the file name. You could just pop up a debugger and see loaded modules.

```
0:000> lm
start    end        module name
00ee0000 00ee6000   ConsoleApplication10   (deferred)             
50190000 5022f000   apphelp    (deferred)             
75ce0000 75dc0000   KERNEL32   (deferred)             
76830000 76a2c000   KERNELBASE   (deferred)            
```

**Comment by MrNasro** [comment]
Great, this is really informative for me rn. Alright I'll close the issue for now, thank you so much for your responsiveness! See you in another issue post maybe? :)
