### ISSUE TITLE
No instrumentation detected for fuzzing a DLL

### ISSUE THREAD

**Issue by kazukiigeta** [googleprojectzero/winafl#247]
Could anyone help me to solve 'PROGRAM ABORT : No instrumentation detected'?

## Original command to cause the error
```
afl-fuzz.exe -i testcases -o results -D c:\dynamorio\build\bin32 -t 50000 -- -coverage_module 7907_fuzz.dll -fuzz_iterations 5000 -target_module harness_crash.exe -target_method fuzz_crash -nargs 1 -- .\harness_crash.exe 7907_fuzz.dll @@
```
The following error output.
```
[-] PROGRAM ABORT : Test case 'id_000000' results in a timeout
         Location : perform_dry_run(), C:\winafl\afl-fuzz.c:2972
```

## Debug command

```
afl-fuzz.exe -i testcases -o results -D c:\dynamorio\build\bin32 -t 50000 -- -coverage_module 7907_fuzz.dll -fuzz_iterations 5000 -target_module harness_crash.exe -target_method fuzz_crash -nargs 1 -debug -- .\harness_crash.exe 7907_fuzz.dll @@
```
Coverage map has only lots of NULL. I think that this leads the error.
I attached the original log.
[afl.harness_crash.exe.01732.0000.proc.log](https://github.com/googleprojectzero/winafl/files/4535246/afl.harness_crash.exe.01732.0000.proc.log)

## Another DLL can be fuzzed normally
Fuzzing normally began though same input file and options are used except the dll.
```
afl-fuzz.exe -i testcases -o results -D c:\dynamorio\build\bin32 -t 10000 -- -coverage_module test_crash.dll -fuzz_iterations 5000 -target_module harness_crash.exe -target_method fuzz_crash -nargs 1 -debug -- .\harness_crash.exe test_crash.dll @@
```

## Environment
```
OS Name:                  Microsoft Windows 10 Pro
OS Version:          10.0.10240 N/A Build 10240

WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>

drrun version 7.91.18357 -- build 0
```

**Comment by hardik05** [comment]
why you are providing dll name after harness? its not needed.
.\harness_crash.exe *test_crash.dll* @@
-Hardik Shah

**Comment by kazukiigeta** [comment]
Thanks for your response. `.\harness_crash.exe` receives a dll as 1st arg and an input file as 2nd arg.
Does my answer become a clue to solve the error?

## Source of harness_crash.exe
```
#include <windows.h>
#include <stdio.h>

extern __declspec(dllexport) void fuzz_crash(wchar_t* wcConfigPath);

typedef int (*INSPECT)(wchar_t *file_path);
INSPECT Crash;

wchar_t* charToWChar(const char* text) {
    size_t size = strlen(text) + 1;
    wchar_t* wa = (wchar_t*)malloc(sizeof(wchar_t) * size);
    mbstowcs(wa, text, size);
    return wa;
}

void fuzz_crash(wchar_t *wcConfigPath) {
    Crash(wcConfigPath);
    return;
}

int main(int argc, char *argv[]) {
    char chFuncName[] = "Crash";

    HMODULE hModule = LoadLibraryA(argv[1]);
    if (hModule == NULL) {
        printf("Failed to load library %s", argv[1]);
        return -1;
    }
    Crash = (INSPECT)GetProcAddress(hModule, chFuncName);
    if (Crash == NULL) {
        printf("%s: GetProcAddress failed.", chFuncName);
        FreeLibrary(hModule);
        return -1;
    }
    fuzz_crash(charToWChar(argv[2]));
    return 0;
}
```

**Comment by kazukiigeta** [comment]
Thanks for your response. `.\harness_crash.exe` receives a dll as 1st arg and an input file as 2nd arg.
Does my answer become a clue to solve the error?

## Source of harness_crash.exe
```
#include <windows.h>
#include <stdio.h>

extern __declspec(dllexport) void fuzz_crash(wchar_t* wcConfigPath);

typedef int (*INSPECT)(wchar_t *file_path);
INSPECT Crash;

wchar_t* charToWChar(const char* text) {
    size_t size = strlen(text) + 1;
    wchar_t* wa = (wchar_t*)malloc(sizeof(wchar_t) * size);
    mbstowcs(wa, text, size);
    return wa;
}

void fuzz_crash(wchar_t *wcConfigPath) {
    Crash(wcConfigPath);
    return;
}

int main(int argc, char *argv[]) {
    char chFuncName[] = "Crash";

    HMODULE hModule = LoadLibraryA(argv[1]);
    if (hModule == NULL) {
        printf("Failed to load library %s", argv[1]);
        return -1;
    }
    Crash = (INSPECT)GetProcAddress(hModule, chFuncName);
    if (Crash == NULL) {
        printf("%s: GetProcAddress failed.", chFuncName);
        FreeLibrary(hModule);
        return -1;
    }
    fuzz_crash(charToWChar(argv[2]));
    return 0;
}
```

> why you are providing dll name after harness? its not needed. .\harness_crash.exe *test_crash.dll* @@ -Hardik Shah

**Comment by hardik05** [comment]
you dont need to provide dll in the args. modify your c program to call dll
function and winafl will take care of the rest.
-Hardik Shah

**Comment by ifratric** [comment]
Hey, check your debug.log - you should see your dll being loaded there and I don't see it in the log you posted. However, note that the dll name seen by the WinAFL and the dll filename might differ (WinAFL uses not the filename but the name as defined in the file itself). From your debug log I see 'Crash104.dll' being loaded, so perhaps that's the name you should be using.

**Comment by kazukiigeta** [comment]
Thank you very much. I can now execute fuzzing without the error by changing the dll name from '7907_fuzz.dll' to 'Crash104.dll'.
