### ISSUE TITLE
unlink  Permission denied(int the function write_to_testcase) 

### ISSUE THREAD

**Issue by hazade** [googleprojectzero/winafl#258]
![image](https://user-images.githubusercontent.com/36125724/89113516-c9960a80-d4a4-11ea-8047-c8af078fe4b6.png)
After i found the second time open failed in the write_to_testcase that caused by O_CREAT | O_EXCL flag, i add PFATAL after unlink.
unlink(out_file); /* Ignore errors. */PFATAL("Unable to unlink '%s'", out_file);
I found that call failed with perm denied

**Comment by hazade** [comment]
> the write_to_testcase that caused by O_CREAT | O_EXCL flag, i add PFATAL after unlink.
> unlink(out_file); /* Ignore errors. */PFATAL("Unable to unlink '%s'", out_file);
> I found that call failed with perm denied

in this case , i also replace the perm flag in open with the value of 0666.
hoping for the help,thanks

**Comment by hazade** [comment]
i overwrite the curinput filename,it works well.

**Comment by hardik05** [comment]
@hazade you can open a pull request. i also face this issue sometime..
