### ISSUE TITLE
Failed to get Trace Version from IPT Service

### ISSUE THREAD

**Issue by bijan-safai** [googleprojectzero/winafl#273]
Hey,

I have been trying to use the fuzzer with IPT instrumentation however when I try to fuzz text.exe I get this error:

C:\FuzzingExp\ALF\ALF\winafl\build64\bin\Release>winaflpt-debug.exe -debug -coverage_module test.exe -fuzz_iterations 10 -target_module test.exe -target_method main -nargs 2 -- test.exe @@
[-] Failed to get Trace Version from IPT Service (err=87)

[-] PROGRAM ABORT : No IPT

         Location : pt_init(), C:\FuzzingExp\ALF\ALF\winafl\winaflpt.c:1585

System info:
OS Name: Microsoft Windows 10 Enterprise
Version: 10.0.19041 Build 19041
Processor: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 2112 Mhz, 4 Core(s), 8 Logical Processor(s)

I have tried to rebuild the project with the -DINTELPT=1 twice (both times pulling the third party dependcies)

Any suggestions would be appreciated, thanks!

**Comment by ifratric** [comment]
Hm, are you running in a VM perhaps?

**Comment by bijan-safai** [comment]
Nope, running on a personal machine. I have been digging around trying to verify that IPT is actually installed, no luck so far however.

**Comment by ifratric** [comment]
Do you also get an error if you just run WinIPT from https://github.com/ionescu007/winipt

**Comment by bijan-safai** [comment]
Yes I do!

C:\FuzzingExp\Ipt\winipt\x64\Release>c:\tools\pslist.exe -d -e notepad -nobanner

notepad 4484:
 Tid Pri    Cswtch            State     User Time   Kernel Time   Elapsed Time
12080  10      2751     Wait:UserReq  0:00:00.031   0:00:00.093    0:02:10.613
24972   8        40       Wait:Queue  0:00:00.000   0:00:00.000    0:02:09.818
19972   8         2       Wait:Queue  0:00:00.000   0:00:00.000    0:02:09.803

C:\FuzzingExp\Ipt\winipt\x64\Release>ipttool.exe --start 4484 200000 1
/-----------------------------------------\
|=== Windows 10 RS5 1809 IPT Test Tool ===|
|===  Copyright (c) 2018 Alex Ionescu  ===|
|===    http://github.com/ionescu007   ===|
|===  http://www.windows-internals.com ===|
\-----------------------------------------/

[*] Size will be aligned to a power of 2
[+] Using size: 131072 bytes
[+] Tracing Options:
           Match by: Any process
         Trace mode: User-mode only
     Timing packets: MTC Packets
[-] Failed to get Trace Version from IPT Service (err=87)

same err=87

**Comment by bijan-safai** [comment]
opened a new issue against winipt here : https://github.com/ionescu007/winipt/issues/9
Thanks for all the help so far!

**Comment by bijan-safai** [comment]
Closed as IPT worked on a different machine (Im guessing the security settings on my work machines were interfering with the library)

**Comment by vmcall** [comment]
Please don't close an issue just because it works on a different machine. This issue is caused by the WinIPT submodule being outdated.

Please clone the latest version of winipt manually into third-party and rebuild WinAFL.

**Comment by ifratric** [comment]
WinAFL should be up to date with latest WinIPT since https://github.com/googleprojectzero/winafl/commit/ea5f6b85572980bb2cf636910f622f36906940aa

**Comment by vmcall** [comment]
And it is not pinned to a specific commit? I had this exact issue due to being on 20H2 which has a different IPT.sys api (and therefore it returns invalid arguments).
Manually pulling the latest commit of WinIPT worked for me
