### ISSUE TITLE
no coverage map on windows10

### ISSUE THREAD

**Issue by testme784** [googleprojectzero/winafl#290]
I downloaded winafl and built with DynamoRIO-Windows-8.0.0-1 on windows10 1511. 
>C:\Users\123\Downloads\DynamoRIO-Windows-8.0.0-1\bin32\drrun.exe -c winafl.dll -debug -target_module test_gdiplus.exe -target_offset 0x10b0 -fuzz_iterations 10 -nargs 2 -- test_gdiplus.exe input.bmp

I also decompiled test_gdiplus.exe to make sure the offset is main. But in log there is no coverage map, only NULL.
![log](https://user-images.githubusercontent.com/67528384/105818946-5ad5cd80-5f6c-11eb-99ee-37a4d8e2cdd0.png)

**Comment by ifratric** [comment]
That's ok. You need to tell it from which module(s) you want coverage (using `-coverage_module` flag) to see anything in the coverage map.

**Comment by houjingyi233** [comment]
Thank you!

**Comment by testme784** [comment]
> That's ok. You need to tell it from which module(s) you want coverage (using `-coverage_module` flag) to see anything in the coverage map.

Thank you!
