### ISSUE TITLE
Windows 10 -  [-] PROGRAM ABORT : Test case 'id_000000' results in a crash 

### ISSUE THREAD

**Issue by samanL33T** [googleprojectzero/winafl#297]
Hi,

I'm trying to fuzzing a DLL using harness and everything works fins when the harness is run directly with DynamoRio and also in debug mode.
However, when I start the fuzzing with afl-fuzz,  I get the following error:

```
[-] PROGRAM ABORT : Test case 'id_000000' results in a crash
         Location : perform_dry_run(), d:\fuzz\winafl-master\afl-fuzz.c:3080
```
Following are my commands:

```
Works-- >D:\Fuzz\DynamoRIO-Windows-7.0.0-RC1\bin64\drrun.exe -c winafl.dll -debug -coverage_module Test.dll -target_module Test.exe -target_offset 0x1070 -fuzz_iterations 10 -nargs 2 -- Test.exe VENUS.WPG  --> WORKS

Works --> afl-showmap.exe -o showmap.txt -D "D:\Fuzz\DynamoRIO-Windows-7.0.0-RC1\bin64" -- -coverage_module Test.dll -fuzz_iterations 5000 -target_module Test.exe -target_offset 0x1070 -nargs 2 -- Test.exe VENUS.WPG  --> WORKS

Fails --> afl-fuzz.exe -i wpg_in -o wpg_out -m none -t 10000+ -D D:\Fuzz\DynamoRIO-Windows-7.0.0-RC1\bin64 -- -target_offset 0x1070 -target_module Test.exe -coverage_module Test.dll -fuzz_iterations 5000 -- Test.exe @@  
```

However, the same thing works on Windows 7 without any problem.

**My system configuration is:**

- Windows 10 1803 (build 17134.1304) (Similar error happens on other Windows 10 builds as well, except for the latest version)
- WinAfl build with following DR versions:
- DynamoRIO-Windows-7.0.0-RC1 (Also tested with DynamoRIO-Windows-8.0.0 -1)
- Harness compiled (x64) using VS2017 

I think I tried pretty much every possible way I could find as a solution in other issues:
- Increased the timeout for initial run
- tried running the harness in debug mode as well as directly with DR
- Disabled anti-virus/Windows Defender real-time protection etc.

Can you please help me figure out what I could be missing?

**Comment by samanL33T** [comment]
Also, for the x86 version of the compiled harness, I couldn't even run it using DR (32 bit) on Windows 10 and receive following error:
I assume, this could be the problem with DR. 
May be it's a different issue in itself

```
D:\Fuzz\DynamoRIO-Windows-7.0.0-RC1\bin32\drrun.exe -- Test_x86.exe VENUS.WPG
<Application D:\Fuzz\winafl-master\build32\bin\Release\Test_x86.exe (3496).  DynamoRIO internal crash at PC 0x5dfefb6b.  Please report this at http://dynamorio.org/issues/.  Program aborted.
0xc0000005 0x00000000 0x5dfefb6b 0x5dfefb6b 0x00000003 0x00000000
Base: 0x5df20000
Registers: eax=0x00000000 ebx=0x0101f140 ecx=0xb786c6f4 edx=0x00000000
        esi=0x21886760 edi=0x21886730 esp=0x0101f160 ebp=0x0101f214
        eflags=0x0001
version 7.0.0, build 1
-no_dynamic_options -code_api -probe_api -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -no_aslr_dr -pad_jmps_mark_no_trace
0x0101f214 0x5dfca31e
0x21886758 0x00000000>
```

**Comment by ifratric** [comment]
On Windows 10, you might want to get a weekly release from https://github.com/DynamoRIO/dynamorio/releases and compile WinAFL with it.

If everything fails, you could try https://github.com/googleprojectzero/Jackalope, it's usage is similar, but it's based on neither DynamoRIO nor AFL, so if it's indeed an instrumentation issue, it might work there (and if it doesn't, at least you'll get a signal that the issue is somewhere else).

**Comment by samanL33T** [comment]
Hi Ivan,
Thanks for the response.

I did try with Jackalope and it works fine.
I will try building winafl with the weekly release of DR and update here shortly.

**Comment by samanL33T** [comment]
Update:

The weekly build of DR solved the issue with x86 harness, which actually solves my purpose.
However, the x64 compiled harness still gives the same error.

I think this narrows down the problem a little towards instrumentation and DR.
