### ISSUE TITLE
Error output suggests removing -t from commandline, but doing so fails.

### ISSUE THREAD

**Issue by jonesmz** [googleprojectzero/winafl#304]
[-] The program took more than 200000 ms to process one of the initial test cases.
    Usually, the right thing to do is to relax the -t option - or to delete it
    altogether and allow the fuzzer to auto-calibrate. That said, if you know
    what you are doing and want to simply skip the unruly test cases, append
    '+' at the end of the value passed to -t ('-t 200000+').

If you remove the -t argument, the afl-fuzz.exe program doesn't run at all, just spits help text at you.

**Comment by ifratric** [comment]
The error messages should be improved with the latest update.
