### ISSUE TITLE
handle leak in afl-fuzz (JobObjects)

### ISSUE THREAD

**Issue by joshpoley** [googleprojectzero/winafl#332]
In afl-fuzz.c, create_target_process(), a windows Job object is created:

    hJob = CreateJobObject(NULL, NULL);

But then is never released with CloseHandle

**Comment by ifratric** [comment]
You're right, thanks for reporting!

https://github.com/googleprojectzero/winafl/commit/c057c74b5b6c840a2620e1bc83cba8a5ed10fffb should fix it, please take a look.

Tentatively closing the issue.
