### ISSUE TITLE
CreateFileMapping failed

### ISSUE THREAD

**Issue by SlidyBat** [googleprojectzero/winafl#334]
When trying to fuzz a target using DynamoRIO I get a `CreateFileMapping failed` error. This error seems to be related to the latest commits that add DR attach functionality. Reverting those commits fixes the issue.

**Comment by ifratric** [comment]
Temporary fix in https://github.com/googleprojectzero/winafl/commit/9471e360fdaf86d64a17bb26c943634299e41629 (reverted part of the patch that caused the issue). Not sure if that breaks the attach mode though.

**Comment by OrBenPorath** [comment]
Sorry about that!
Apparently `CreateFileMapping` with `Global` requires admin privileges.

It does not break attach, just requires that afl-fuzz and the target run under the same session (which I was trying to avoid for ease of use).

**Comment by ifratric** [comment]
Sounds like this issue can be closed now.
