### ISSUE TITLE
ASSERT FAILURE: C:\Code\MyResearch\winafl\winafl.c:969: (0) (invalid option)

### ISSUE THREAD

**Issue by eranzim** [googleprojectzero/winafl#340]
I'm trying to run winafl with a simple harness, and get this error:
```
---------------------------
WinAFL Notice: C:\Code\Test\TestExe\x64\Release\TestExe.exe(18828)
---------------------------
ASSERT FAILURE: C:\Code\MyResearch\winafl\winafl.c:969: (0) (invalid option)
---------------------------
OK   
---------------------------
```
I simplified the harness to be an empty _tmain function (just returns 0, nothing more), and this still happens.
This is the command line I used and output with the original harness:
```
# afl-fuzz.exe -i in -o out -D C:\Code\MyResearch\DynamoRIO-Windows-8.0.18936\bin64 -t 1000 -- -late -debug -coverage_module dfdll.dll -fuzz_iterations 10 -target_module TestExe.exe -target_method fuzzme -nargs 2 -- C:\Code\Test\TestExe\x64\Release\TestExe.exe @@
WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
[+] You have 8 CPU cores and 0 runnable tasks (utilization: 0%).
[+] Try parallel jobs - see afl_docs\parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[+] Process affinity is set to 1.

[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
0 processes nudged
nudge operation failed, verify permissions and parameters.
ERROR: The process "-1" not found.

[-] The program took more than 1000 ms to process one of the initial test cases.
    In WinAFL, this error could also mean incorrect instrumentation params.
    Please make sure instrumentation runs correctly using the debug mode
    (see the README) before attempting to run afl-fuzz.

[-] PROGRAM ABORT : Test case 'id_000000' results in a timeout
         Location : perform_dry_run(), C:\Code\MyResearch\winafl\afl-fuzz.c:3214
```

And this is with the 'return 0' executable (slightly different error, probably because the fuzzme function doesn't exist here, but if I do add the function - even if it's not called - the output is like the previous one):
```
# afl-fuzz.exe -i in -o out -D C:\Code\MyResearch\DynamoRIO-Windows-8.0.18936\bin64 -t 1000 -- -late -debug -coverage_module dfdll.dll -fuzz_iterations 10 -target_module TestExe.exe -target_method fuzzme -nargs 2 -- C:\Code\Test\TestExe\x64\Release\TestExe.exe @@
WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
[+] You have 8 CPU cores and 0 runnable tasks (utilization: 0%).
[+] Try parallel jobs - see afl_docs\parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[+] Process affinity is set to 1.

[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
0 processes nudged
nudge operation failed, verify permissions and parameters.
ERROR: The process "-1" not found.

[-] PROGRAM ABORT : Cannot kill child process

         Location : destroy_target_process(), C:\Code\MyResearch\winafl\afl-fuzz.c:2629
```

Both popped the aforementioned message box.

This seems to work:
```
C:\Code\MyResearch\DynamoRIO-Windows-8.0.18936\bin64\drrun.exe -late -c winafl.dll -debug -target_module TestExe.exe -coverage_module dfdll.dll -target_method fuzzme -fuzz_iterations 10 -nargs 2 -- C:\Code\Test\TestExe\x64\Release\TestExe.exe @@
```

By the way, the `-late` flag is used due to this bug: https://github.com/DynamoRIO/dynamorio/issues/5198

Using latest DynamoRIO release (DynamoRIO-Windows-8.0.18936.zip), Windows 10 21H1 (OS build 19043.1320). 64-bit versions for everything.

**Comment by expend20** [comment]
Place `-late` before first `--` ?

**Comment by ifratric** [comment]
Some other issues I see:

 - You should not use `-debug` flag together with `afl-fuzz.exe`. `-debug` is for standalone winafl.dll debugging only (which you should do prior to running afl-fuzz as it generates a log that can help with debugging issues like you encountered). See Readme for more details.
 
 - You wrote `I simplified the harness to be an empty _tmain function (just returns 0, nothing more)`, but you specified `-target_method fuzzme`. Since in this case `fuzzme` will never be reached, WinAFL is going to treat it as a hang.

**Comment by eranzim** [comment]
I removed `-debug`, still getting the same error. Moving `-late` to before the first `--` gives this error:
```
# ERROR: The process "-1" not found.
afl-fuzz.exe -i in -o out -D C:\Code\MyResearch\DynamoRIO-Windows-8.0.18936\bin64 -t 1000 -late -- -coverage_module dfdll.dll -fuzz_iterations 10 -target_module TestExe.exe -target_method fuzzme -nargs 2 -- C:\Code\Test\TestExe\x64\Release\TestExe.exe @@
WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
Loading custom winAFL server library

[-] PROGRAM ABORT : Unable to load custom server library, GetLastError = 0x7e
         Location : load_custom_library(), C:\Code\MyResearch\winafl\afl-fuzz.c:8016
```

My logic was that this is a flag for DynamoRIO, so should be after the first `--`.

(these are with the harness that does call fuzzme, as per @ifratric 's correct observation)

**Comment by ifratric** [comment]
Seems it's not as simple to pass the `-late` flag. It should be passed to `drrun.exe` in a very specific position (before the client params) and I don't think it's possible to do it like that. (Above, afl-fuzz is interpreting it as its `-l` flag, that's why you get that error).

You should be able to add that flag in the source code here https://github.com/googleprojectzero/winafl/blob/master/afl-fuzz.c#L2469 and in other places in the same function where drrun.exe is referenced.

**Comment by sgabe** [comment]
@eranzim, you might be able to use the `-late` flag by adding the line `DR_OP=-no_early_inject` to the tool configuration file as mentioned in #336.

**Comment by eranzim** [comment]
As of the latest release (https://github.com/DynamoRIO/dynamorio/releases/tag/cronbuild-8.0.18942-1), the `-late` flag is no longer needed, and I no longer get an error, so I think it's safe to close this issue. Thanks!
