### ISSUE TITLE
option -A(attach) is not working 

### ISSUE THREAD

**Issue by kismp123** [googleprojectzero/winafl#348]
I'm trying to use -A option (attach)
however somewhere called function "destroy_target_process" and changed attach pid
```
  if (drattach) {
    // reset the attach pid for next round
    drattachpid = 0;
  }
```
as result ran below code with child_pid == 0
child_handle = OpenProcess(PROCESS_ALL_ACCESS, FALSE, child_pid);

log is here 
```
WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
Loading custom winAFL server library
dll_init is defined.
dll_run_ptr is defined.
dll_run_target isn't defined.
dll_write_to_testcase isn't defined.
dll_mutate_testcase isn't defined.
dll_trim_testcase isn't defined.
dll_mutate_testcase_with_energy isn't defined.
Sucessfully loaded and initalized
[+] You have 8 CPU cores with average utilization of 3%.
[+] Try parallel jobs - see afl_docs\parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[+] Process affinity is set to 1.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
Ready to begin fuzzing. Target IP= 127.0.0.1, target port = 39721

[-] PROGRAM ABORT : OpenProcess failed, GLE=87.

         Location : create_target_process(), C:\Users\-\Downloads\winafl\afl-fuzz.c:2557
```

it's my commands 
```
set AFL_CUSTOM_DLL_ARGS=-p 39721 -a 127.0.0.1 -w 1000

afl-fuzz.exe -A KCaseLib.exe -l custom_net_fuzzer.dll -i in -o out -D C:\Users\-\Downloads\DynamoRIO-Windows-8.0.0-1\bin32 -t 100+ -- -coverage_module KcaseCms.dll -coverage_module KcaseCommon.dll -coverage_module KcaseCrypto.dll -fuzz_iterations 5000 -target_module KCaseLib.exe -target_offset 0x22620 -persistence_mode in_app -- "C:\Program Files (x86)\Ksign\KCase\KCaseLib.exe"
```

anyone can give me an example to use attach ??

**Comment by ifratric** [comment]
@OrBenPorath would appreciate if you could take a look.

**Comment by OrBenPorath** [comment]
When using the attach option, the target is not started, nor is it restarted when it is terminated (which is the expected behaviour in several cases), so one needs to start it externally whenever it is down.

It seems that `find_attach_pid` did not find the a process with this module. The check in `module_loaded_to_pid` is a case sensitive comparison between the supplied module name, and the name returned from `Module32First`/`Module32Next`.

@kismp123 Can you verify that the target process is up when trying to attach, and that the module is loaded with the expected name and case using `Module32First`,`Module32Next`.

In any case, it would probably be best to explicitly throw an error if we do not find a target process, and change the module name comparison to be case insensitive.

**Comment by kismp123** [comment]
I added some print in function "create_target_process" to verify drattachpid
```
  FUZZ_LOG("drattachpid = %d\n", drattachpid);          <-- added
  if(!OverlappedConnectNamedPipe(pipe_handle, &pipe_overlapped)) {
      FATAL("ConnectNamedPipe failed, GLE=%d.\n", GetLastError());
  }
  FUZZ_LOG("drattachpid = %d\n", drattachpid);          <-- added
  watchdog_enabled = 0;

  if (drattach) {
    child_pid = drattachpid;
    FUZZ_LOG("attach pid -> %d\n", child_pid);          <-- added
    CloseHandle(child_handle);
    child_handle = OpenProcess(PROCESS_ALL_ACCESS, FALSE, child_pid);
    if (child_handle == NULL)
    {
      FATAL("OpenProcess failed, GLE=%d.\n", GetLastError());
    }

    CloseHandle(child_thread_handle);
    child_thread_handle = NULL;
  }
```

log is here 
```
drattachpid = 20380
drattachpid = 20380
called destory_target_process()
drattachpid = 0
attach pid -> 0
```

after called "destroy_target_process", process is still running.

**Comment by OrBenPorath** [comment]
Great, so we are finding the target properly.

The only reason I can see for this flow:
>drattachpid = 20380
>called destroy_target_process()
>drattachpid = 0
>attach pid -> 0

is that the watchdog times out before the target connects to the pipe. 
There are two possible reasons for it from the `drrun.exe` side:
1. attach takes too long.
2. attach fails.

accordingly, I would suggest:
1. increase the timeout (I doubt it will solve the issue, but worth the shot). 
2. run the actual `drrun.exe` command line from cmd, and see if there are any errors. 
one possible error is not enough permissions to open the target process with PROCESS_ALL_ACCESS.

**Comment by kismp123** [comment]
I logged again 

```
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
Ready to begin fuzzing. Target IP= 127.0.0.1, target port = 39721
C:\Users\-\Downloads\DynamoRIO-Windows-8.0.0-1\bin32\drrun.exe -attach 7804 -no_follow_children -c winafl.dll -coverage_module KcaseCms.dll -coverage_module KcaseCommon.dll -coverage_module KcaseCrypto.dll -fuzz_iterations 5000 -target_module KCaseLib.exe -target_offset 0x22620 -persistence_mode in_app -fuzzer_id 75028911141b71ef
drattachpid = 7804
drattachpid = 7804
destory_target_process()
drattachpid = 0
attach pid -> 0
```

I got ```C:\Users\-\Downloads\DynamoRIO-Windows-8.0.0-1\bin32\drrun.exe -attach 7804 -no_follow_children -c winafl.dll -coverage_module KcaseCms.dll -coverage_module KcaseCommon.dll -coverage_module KcaseCrypto.dll -fuzz_iterations 5000 -target_module KCaseLib.exe -target_offset 0x22620 -persistence_mode in_app -fuzzer_id 75028911141b71ef```

and I ran this command

```
C:\Users\-\Downloads\winafl\build32\bin\Release>C:\Users\-\Downloads\DynamoRIO-Windows-8.0.0-1\bin32\drrun.exe -attach 7804 -no_follow_children -c winafl.dll -coverage_module KcaseCms.dll -coverage_module KcaseCommon.dll -coverage_module KcaseCrypto.dll -fuzz_iterations 5000 -target_module KCaseLib.exe -target_offset 0x22620 -persistence_mode in_app -fuzzer_id 75028911141b71ef
ERROR: no app specified

USAGE: drrun [options] <app and args to run>
   or: drrun [options] -- <app and args to run>
   or: drrun [options] [DR options] -- <app and args to run>
   or: drrun [options] [DR options] -c <client> [client options] -- <app and args to run>
   or: drrun [options] [DR options] -t <tool> [tool options] -- <app and args to run>
       available tools include: drcachesim, drcov, drcpusim, drmemory, drmemory_light, handle_leaks, drstrace
Run with -help to see drrun option list
```

**Comment by OrBenPorath** [comment]
In that case, I think the error is much simpler: DynamoRIO 8.0.0 does not support attach. Try to run it with the latest DR release.

Also, the bitness of `drrun` and the target must be the same. Is the target also 32 bit?

The minimal required DR version should probably be documented (maybe after v9 is released, the documentation should just require v9).

**Comment by kismp123** [comment]
yes target is 32bit.
I can't find version 9 of DR. lastest is 8.0.18962
https://github.com/DynamoRIO/dynamorio/releases

**Comment by OrBenPorath** [comment]
Yes, DR v9 is not out yet, but latest minor version should have attach functionality.

Same error in `afl-fuzz`? What about the `drrun` command? Same error?

**Comment by kismp123** [comment]
same error in afl-fuzz 

when I do drrun command, there is no output.
however when I sent packet I got this message.
```
---------------------------
WinAFL Notice: C:\Program Files (x86)\KSIGN\KCase\KCaseLib.exe(6180)
---------------------------
ASSERT FAILURE: C:\Users\-\Downloads\winafl\winafl.c:486: false (unrecognized command received over pipe:)
---------------------------
확인   
---------------------------
```

**Comment by kismp123** [comment]
I think it works 
I need to change my test cases haha
ty :D

```
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
Ready to begin fuzzing. Target IP= 127.0.0.1, target port = 39721
destory_target_process()C:\Users\-\Downloads\DynamoRIO-Windows-8.0.18962\bin32\drrun.exe -attach 17792 -no_follow_children -c winafl.dll -coverage_module KcaseCms.dll -coverage_module KcaseCommon.dll -coverage_module KcaseCrypto.dll -fuzz_iterations 5000 -target_module KCaseLib.exe -target_offset 0x22620 -persistence_mode in_app -fuzzer_id 6c710d71529e45f9
drattachpid = 17792
drattachpid = 17792
drattachpid = 17792
attach pid -> 17792
destory_target_process()1 processes nudged
[!] WARNING: Test case results in a timeout (skipping)
[*] Attempting dry run with 'id_000001'...
destory_target_process()C:\Users\-\Downloads\DynamoRIO-Windows-8.0.18962\bin32\drrun.exe -attach 0 -no_follow_children -c winafl.dll -coverage_module KcaseCms.dll -coverage_module KcaseCommon.dll -coverage_module KcaseCrypto.dll -fuzz_iterations 5000 -target_module KCaseLib.exe -target_offset 0x22620 -persistence_mode in_app -fuzzer_id 6c710d71529e45f9
drattachpid = 0
drattachpid = 0
destory_target_process()drattachpid = 0
attach pid -> 0

[-] PROGRAM ABORT : OpenProcess failed, GLE=87.

         Location : create_target_process(), C:\Users\-\Downloads\winafl\afl-fuzz.c:2557

```

**Comment by LvHongW** [comment]
I ran into the same problem as you. so how you solved it：
PS C:\Windows\system32> D:\RumpusFTP\winafl\build\bin\Release\afl-fuzz.exe -i D:\RumpusFTP\winafl\workdir\in -o D:\RumpusFTP\winafl\workdir\out -A rumpusd.exe  -l D:\RumpusFTP\winafl\build\bin\Release\custom_net_fuzzer.dll -w D:\RumpusFTP\winafl\build\bin\Release\winafl.dll -D D:\RumpusFTP\winafl\DynamoRIO-Windows-11.90.20418\bin64 -t 40000 -- -debug -covtype edge -coverage_module rumpusd.exe -target_module rumpusd.exe -target_offset 0xF2D90 -fuzz_iterations 5000 -- C:\Rumpus\ApplicationFiles\rumpusd.exe
WinAFL 1.17 by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
Loading custom winAFL server library
dll_init is defined.
dll_run_ptr is defined.
dll_run_target isn't defined.
dll_write_to_testcase isn't defined.
dll_mutate_testcase isn't defined.
dll_trim_testcase isn't defined.
dll_mutate_testcase_with_energy isn't defined.
Sucessfully loaded and initalized
[+] You have 16 CPU cores with average utilization of 0%.
[+] Try parallel jobs - see afl_docs\parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[+] Process affinity is set to 1.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'D:\RumpusFTP\winafl\workdir\in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...
Ready to begin fuzzing. Target IP= 127.0.0.1, target port = 8124
0 processes nudged
nudge operation failed, verify permissions and parameters.
错误: 没有找到进程 "-1"。

[-] PROGRAM ABORT : Cannot kill child process

         Location : destroy_target_process(), D:\RumpusFTP\winafl\afl-fuzz.c:2666
