### ISSUE TITLE
Assert Failure (invalid option)

### ISSUE THREAD

**Issue by mehdighninoudev** [googleprojectzero/winafl#367]
Hi, I have a problem please ? When I execute this command: 
afl-fuzz -i in -o out  -t 3000+ -D "C:\Users\User\Desktop\Tools\Fuzzing\DRRUN\DynamoRIO-Windows-8.0.18929\bin64" -w winafl.dll   -coverage_module dllmain.dll -coverage_module dllmain2.dll -coverage_module dllmain3.dll -target_module program.exe -target_method WinMain -c 2 -- "program.exe" @@

I got this error:  ASSERT FAILURE: C:\Users\user\desktop\tools\fuzzing\drrun\winafl\winafl.c:969: (0)
(invalid option)

How to resolve the problem and fuzz the binary please ?

**Comment by ifratric** [comment]
WinAFL usage is

`afl-fuzz [afl options] -- [instrumentation options] -- target_cmd_line`

you're missing `--` between afl and instrumentation options.

**Comment by mehdighninoudev** [comment]
Do you mean that the cmd need to be like that : 
`afl-fuzz -i in -o out -t 3000+ -- -D "C:\Users\User\Desktop\Tools\Fuzzing\DRRUN\DynamoRIO-Windows-8.0.18929\bin64" -w winafl.dll -coverage_module dllmain.dll -coverage_module dllmain2.dll -coverage_module dllmain3.dll -target_module program.exe -target_method WinMain -- -c 2 -- "program.exe" @@`

But I have tried and it give me the help usage ?

**Comment by ifratric** [comment]
Please see examples in https://github.com/googleprojectzero/winafl/blob/master/readme_dr.md

**Comment by mehdighninoudev** [comment]
sure thank you
