### ISSUE TITLE
ASSERT FAILURE winafl.c:526: fase (unrecognized command received over pipe)

### ISSUE THREAD

**Issue by RIeFre** [googleprojectzero/winafl#386]
Everytime I stop fuzzing with CTRL+C, this error popup. I tried on Windows 10 with DynamoRIO 7, 8, and 9 versions.  Is this normal?

![屏幕截图 2022-08-26 102342](https://user-images.githubusercontent.com/5643387/186803129-33e595c2-9e6a-4f6e-8639-e60b209d51af.png)

**Comment by ifratric** [comment]
Yes, that's normal. When you stop the fuzzer process, the target process might continue running for a short while. If the target process is in a state where it's expecting to receive a command from the fuzzer via pipe, and that command doesn't come, you get an error message like this.

**Comment by RIeFre** [comment]
Is it possible  to write a command to tell the target to exit before fuzzer stop?

**Comment by ifratric** [comment]
It should be possible to do.

**Comment by RIeFre** [comment]
Thanks. I will try it.
