### ISSUE TITLE
Cannot run simple test due to timeout

### ISSUE THREAD

**Issue by MakotoE** [googleprojectzero/winafl#408]
I can't fuzz this simple program compiled with Visual Studio, Debug configuration.

```c++
#include <iostream>

int main()
{
    std::cout << "Hello world";
}
```

I compiled winafl using the following commands.

```
cmake -G"Visual Studio 17 2022" -A x64 .. -DDynamoRIO_DIR="...\DynamoRIO-Windows-9.93.19475\cmake" -DUSE_DRSYMS=1

cmake --build . --config Release
```

I checked that winafl recognizes the main function with the following powershell script.

```
. "...\drrun.exe" `
	-c "...\winafl.dll" `
	-debug `
	-target_module winafl-test.exe `
	-target_method main `
	-nargs 0 `
	-fuzz_iterations 1 `
	-- "...\winafl-test\x64\Debug\winafl-test.exe"
```

The log file included `Module loaded, winafl-test.exe` and 

```
In pre_fuzz_handler
In post_fuzz_handler
Everything appears to be running normally.
```

so I know that it worked up to this much. The issue was when running `afl-fuzz.exe`.

```
. "...\afl-fuzz.exe" `
	-i input `
	-o output `
	-t 1000 `
	-D "...\DynamoRIO-Windows-9.93.19475\bin64" `
	-- `
	-target_module winafl-test.exe `
	-target_method main `
	-nargs 0 `
	-fuzz_iterations 1 `
	-- "...\winafl-test\x64\Debug\winafl-test.exe"
```

It outputs:

```
WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>
[+] You have 24 CPU cores with average utilization of 1%.
[+] Try parallel jobs - see afl_docs\parallel_fuzzing.txt.
[*] Checking CPU core loadout...
[+] Found a free CPU core, binding to #0.
[+] Process affinity is set to 1.
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'input'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Attempting dry run with 'id_000000'...

[-] The program took more than 1000 ms to process one of the initial test cases.
    In WinAFL, this error could also mean incorrect instrumentation params.
    Please make sure instrumentation runs correctly using the debug mode
    (see the README) before attempting to run afl-fuzz.

[-] PROGRAM ABORT : Test case 'id_000000' results in a timeout
         Location : perform_dry_run(), C:\Users\MakotoEmura\Downloads\winafl-master\afl-fuzz.c:3232
```

I think I'm missing some obvious requirement because the simple program doesn't work. I wish there was a sample project we could clone and run the fuzz test on our machines to have a concrete example.

Some system info: Windows 11, Visual Studio 2022, DynamoRIO 9.93.19475, winafl commit `4071f169a161b6368c09fd3ff1fd742c08164fa4`.

**Comment by MakotoE** [comment]
Update: I tried the same steps but on a Windows 10 virtual machine and the same thing happened.

**Comment by goldstar611** [comment]
[test_gdiplus.exe](https://github.com/googleprojectzero/winafl/blob/master/gdiplus.cpp) is built with winafl and is a great resource

https://github.com/googleprojectzero/winafl/blob/38297efbf227aec2c5696b5581fa661e744bdc2a/readme_dr.md?plain=1#L132-L137

**Comment by J-jaeyoung** [comment]
If you run `afl-fuzz.exe` from a location other than the directory containing both `afl-fuzz.exe` and `winafl.dll`, you have to specify the path of `winafl.dll` using `-w` option. 

```
C:\winafl\build\bin\Release\afl-fuzz.exe -w C:\winafl\build\bin\Release\winafl.dll <remaining options unchanged>
```

**Comment by MakotoE** [comment]
Thanks to both [goldstar611](https://github.com/goldstar611)'s recommendation to use the existing example and [J-jaeyoung](https://github.com/J-jaeyoung)'s recommendation to add the `-w` flag, I got it to work as expected. The flags I added are `-w` and `-coverage_module`.

Now the full command is

```
. "C:\Users\MakotoEmura\Downloads\winafl\build\bin\Release\afl-fuzz.exe" `
	-i input `
	-o output `
	-t 1000 `
	-D "C:\Users\MakotoEmura\Downloads\DynamoRIO-Windows-10.0.0\bin64" `
	-w "C:\Users\MakotoEmura\Downloads\winafl\build\bin\Release\winafl.dll" `
	-- `
	-target_module fuzz-test.exe `
	-target_method main `
	-coverage_module gdiplus.dll `
	-coverage_module WindowsCodecs.dll `
	-fuzz_iterations 10 `
	-- "C:\Users\MakotoEmura\Downloads\fuzz-test\x64\Debug\fuzz-test.exe" `@`@
```

I was also able to do the In App Persistence mode without any issues after this.
