### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by 20urc3** [googleprojectzero/winafl#409]
Some information in the docs can be misleading : https://github.com/googleprojectzero/winafl/blob/4071f169a161b6368c09fd3ff1fd742c08164fa4/afl_docs/technical_details.txt#L416 

WinAFL doesn't use Fork()

**Comment by ifratric** [comment]
Hi, the docs under `afl_docs` are original, unmodified (linux) AFL documents and thus not everything may apply to WinAFL.

BTW thanks for writing https://bushido-sec.com/index.php/2023/06/25/the-art-of-fuzzing-windows-binaries/

**Comment by 20urc3** [comment]
Hi @ifratric , indeed make sense. Thanks for your feedback, appreciate it! Let's discuss some times, Twitter?

**Comment by ifratric** [comment]
Sure, my DMs are open.
