### ISSUE TITLE
Timeout Options Madness

### ISSUE THREAD

**Issue by joseph-giron** [googleprojectzero/winafl#445]
I am going a little crazy here. What am I doing wrong? It complains when I have the option -t, and it complains when I don't
I guess there's no running the program. Its claiming multiple options. No matter how I re-arrange the options, same result.
Any help would be nice. 

D:\winafl\bin32>afl-fuzz.exe -t 10000 -i inputs -o outputs -D D:\DRIO8 -target_module my_prog.exe -coverage_module my_prog.exe -- a:\downloads\my_prog\my_prog.exe @@
WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>

[-] PROGRAM ABORT : Multiple -t options not supported
         Location : main(), c:\work\winafl\source\afl-fuzz.c:7781

D:\winafl\bin32>afl-fuzz.exe -i inputs -o outputs -D D:\DRIO8 -target_module my_prog.exe -coverage_module my_prog.exe -- a:\downloads\my_prog\my_prog.exe @@
WinAFL 1.16b by <ifratric@google.com>
Based on AFL 2.43b by <lcamtuf@google.com>

[-] PROGRAM ABORT : Bad syntax used for -t
         Location : main(), c:\work\winafl\source\afl-fuzz.c:7784

**Comment by ifratric** [comment]
From a quick look you seem to be missing `--` between `afl-fuzz` arguments and instrumentation arguments. That's why `-target_module` gets misinterpreted as `-t` flag and you get errors you are getting.

**Comment by joseph-giron** [comment]
@ifratric thanks!
