### ISSUE TITLE
Fuzzing Windows service

### ISSUE THREAD

**Issue by mxmssh** [googleprojectzero/winafl#84]
Hi, thank you for WinAFL. I have a question.

Suppose I want to fuzz Windows service. Unfortunately, I can't just execute it from WinAFL, I can only attach   to it after initialization finished. Is there a way to attach WinAFL into the running process ? 

Thank you.

**Comment by ivanfratric** [comment]
Currently, no.

AFAIK there is an option in DynamoRIO to always attach to a process with a given name (see http://dynamorio.org/docs/page_deploy.html) so that's something you might try playing with, though it would require some changes in WinAFL.

**Comment by mxmssh** [comment]
Ok, thank you, I am planning to implement this functionality. Could you point me which WinAFL functions would likely be changed ?

**Comment by 1n598** [comment]
Mostly all of the things. I have tried writing a wrapper over the winsock2
calls but it seemed that I will be creating more issues with my hook than
with fuzzing. Also, other limitation is that you will not be able to fuzz
sessions in network protocols, which is a bummer.

**Comment by 1n598** [comment]
Sorry for the direct mail. It was supposed to answer the thread.

**Comment by mxmssh** [comment]
Well, thanks for sharing experience. In my case it is an application that receives UDP packages in one function and parse them in another. Thereby, I don't need to wrap the winsock2. I just need a wrapper for the function that parse content of UDP package.

**Comment by wangkai0351** [comment]
I am doing the same attempt, modifying WinAFL and enabling it to be attached to the fuzzing test of Windows system services. Windows Service Control Manager(SCM)  is a obstacle.
I also want to know more about which WinAFL functions would likely be changed？

**Comment by ifratric** [comment]
Note that, unlike DynamoRIO, my recent instrumentation project TinyInst (https://github.com/googleprojectzero/TinyInst) has an ability to attach to a running process, so it could be used to fuzz Windows services. TinyInst is just an instrumentation (without the fuzzing stuff), but it's used by several fuzzers e.g. Jackalope (https://github.com/googleprojectzero/Jackalope). Jackalope  does not currently take advantage of attaching functionality of TinyInst. However, contributions are welcome :-)

**Comment by sgabe** [comment]
This seems to be resolved by #333.

**Comment by ifratric** [comment]
Yep, should be doable now with attach functionality.
